# Generated by Django 6.0.3 on 2026-03-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Company name used in email templates (for {{ company_name }})",
                max_length=255,
            ),
        ),
    ]
