# Generated by Django 6.0.3 on 2026-03-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_emailtemplate_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Company name used in email templates (for {{ company_name }})",
                max_length=255,
                null=True,
            ),
        ),
    ]
