# Generated by Django 6.0.3 on 2026-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaigntarget_business_unit_campaigntarget_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Optional signature image (e.g. company logo or sender signature). Automatically appended to the bottom of every email sent using this template. Embedded as a base64 inline image — no external hosting needed.', null=True, upload_to='template_signatures/'),
        ),
    ]
