# Generated by Django 6.0.3 on 2026-03-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='caption',
            field=models.CharField(blank=True, help_text='Short subtitle shown below the title, e.g. "Beginner · 30 min"', max_length=255),
        ),
    ]
