export const campaigns = [
    {
        id: 1,
        name: 'Phishing Simulation Campaign 1',
        status: 'Cancelled',
        target: 'All employees',
        date: '2026-01-05',
        completion: '0%',
        subject: 'Email subject 1',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 2,
        name: 'Phishing Simulation Campaign 2',
        status: 'Completed',
        target: 'All employees',
        date: '2026-01-12',
        completion: '100%',
        subject: 'Email subject 2',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 3,
        name: 'Phishing Simulation Campaign 3',
        status: 'Active',
        target: 'IT Department',
        date: '2026-01-19',
        completion: '45%',
        subject: 'Email subject 3',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 4,
        name: 'Phishing Simulation Campaign 4',
        status: 'Draft',
        target: 'Finance Team',
        date: '2026-01-26',
        completion: '0%',
        subject: 'Email subject 4',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 5,
        name: 'Phishing Simulation Campaign 5',
        status: 'Completed',
        target: 'All employees',
        date: '2026-02-02',
        completion: '100%',
        subject: 'Email subject 5',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 6,
        name: 'Phishing Simulation Campaign 6',
        status: 'Active',
        target: 'All employees',
        date: '2026-02-09',
        completion: '72%',
        subject: 'Email subject 6',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 7,
        name: 'Phishing Simulation Campaign 7',
        status: 'Completed',
        target: 'Executive Board',
        date: '2026-02-16',
        completion: '100%',
        subject: 'Email subject 7',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 8,
        name: 'Phishing Simulation Campaign 8',
        status: 'Draft',
        target: 'All employees',
        date: '2026-02-23',
        completion: '0%',
        subject: 'Email subject 8',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 9,
        name: 'Phishing Simulation Campaign 9',
        status: 'Cancelled',
        target: 'Sales Team',
        date: '2026-03-02',
        completion: '0%',
        subject: 'Email subject 9',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 10,
        name: 'Phishing Simulation Campaign 10',
        status: 'Completed',
        target: 'All employees',
        date: '2026-03-09',
        completion: '100%',
        subject: 'Email subject 10',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 11,
        name: 'Phishing Simulation Campaign 11',
        status: 'Active',
        target: 'All employees',
        date: '2026-03-16',
        completion: '88%',
        subject: 'Email subject 11',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 12,
        name: 'Phishing Simulation Campaign 12',
        status: 'Draft',
        target: 'HR Department',
        date: '2026-03-23',
        completion: '0%',
        subject: 'Email subject 12',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 13,
        name: 'Phishing Simulation Campaign 13',
        status: 'Completed',
        target: 'All employees',
        date: '2026-03-30',
        completion: '100%',
        subject: 'Email subject 13',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 14,
        name: 'Phishing Simulation Campaign 14',
        status: 'Cancelled',
        target: 'All employees',
        date: '2026-04-06',
        completion: '0%',
        subject: 'Email subject 14',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 15,
        name: 'Phishing Simulation Campaign 15',
        status: 'Completed',
        target: 'IT Department',
        date: '2026-04-13',
        completion: '100%',
        subject: 'Email subject 15',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 16,
        name: 'Phishing Simulation Campaign 16',
        status: 'Active',
        target: 'All employees',
        date: '2026-04-20',
        completion: '34%',
        subject: 'Email subject 16',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 17,
        name: 'Phishing Simulation Campaign 17',
        status: 'Draft',
        target: 'All employees',
        date: '2026-04-27',
        completion: '0%',
        subject: 'Email subject 17',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 18,
        name: 'Phishing Simulation Campaign 18',
        status: 'Completed',
        target: 'Contractors',
        date: '2026-05-04',
        completion: '100%',
        subject: 'Email subject 18',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 19,
        name: 'Phishing Simulation Campaign 19',
        status: 'Cancelled',
        target: 'All employees',
        date: '2026-05-11',
        completion: '0%',
        subject: 'Email subject 19',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 20,
        name: 'Phishing Simulation Campaign 20',
        status: 'Active',
        target: 'All employees',
        date: '2026-05-18',
        completion: '95%',
        subject: 'Email subject 20',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec imperdiet nisl, non porta velit. In a neque non diam tincidunt gravida eget ac turpis. Maecenas tincidunt bibendum lacus sit amet finibus. Curabitur arcu risus, venenatis id vulputate vel, vulputate ut eros. Nunc viverra, risus id varius facilisis, nunc ante sodales lectus, id dictum velit nisl sed tortor. Morbi rhoncus arcu nibh, a ullamcorper enim posuere sit amet. Duis hendrerit placerat risus ac pharetra. Morbi sed dui eleifend, tempus neque vel, accumsan nulla. Aenean a tellus molestie, vestibulum purus quis, egestas massa. Aenean suscipit purus et condimentum molestie. Curabitur id congue risus, sed scelerisque elit. Nunc consequat feugiat ex at gravida. Phasellus ac erat at risus scelerisque viverra in eu eros. Duis malesuada fermentum dolor, eu iaculis tortor porta eu. Pellentesque pulvinar lectus lacinia, pellentesque libero et, tristique ipsum.',
    },
    {
        id: 21,
        name: 'Phishing Simulation Campaign 21',
        status: 'Completed',
        target: 'All employees',
        date: '2026-05-25',
        completion: '100%',
        subject: 'Email subject 21',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 22,
        name: 'Phishing Simulation Campaign 22',
        status: 'Draft',
        target: 'Sales Team',
        date: '2026-06-01',
        completion: '0%',
        subject: 'Email subject 22',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 23,
        name: 'Phishing Simulation Campaign 23',
        status: 'Active',
        target: 'All employees',
        date: '2026-06-08',
        completion: '15%',
        subject: 'Email subject 23',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 24,
        name: 'Phishing Simulation Campaign 24',
        status: 'Cancelled',
        target: 'Finance Team',
        date: '2026-06-15',
        completion: '0%',
        subject: 'Email subject 24',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 25,
        name: 'Phishing Simulation Campaign 25',
        status: 'Completed',
        target: 'All employees',
        date: '2026-06-22',
        completion: '100%',
        subject: 'Email subject 25',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 26,
        name: 'Phishing Simulation Campaign 26',
        status: 'Active',
        target: 'HR Department',
        date: '2026-06-29',
        completion: '60%',
        subject: 'Email subject 26',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 27,
        name: 'Phishing Simulation Campaign 27',
        status: 'Completed',
        target: 'All employees',
        date: '2026-07-06',
        completion: '100%',
        subject: 'Email subject 27',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 28,
        name: 'Phishing Simulation Campaign 28',
        status: 'Draft',
        target: 'IT Department',
        date: '2026-07-13',
        completion: '0%',
        subject: 'Email subject 28',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 29,
        name: 'Phishing Simulation Campaign 29',
        status: 'Completed',
        target: 'All employees',
        date: '2026-07-20',
        completion: '100%',
        subject: 'Email subject 29',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 30,
        name: 'Phishing Simulation Campaign 30',
        status: 'Active',
        target: 'All employees',
        date: '2026-07-27',
        completion: '82%',
        subject: 'Email subject 30',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 31,
        name: 'Phishing Simulation Campaign 31',
        status: 'Cancelled',
        target: 'Executive Board',
        date: '2026-08-03',
        completion: '0%',
        subject: 'Email subject 31',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 32,
        name: 'Phishing Simulation Campaign 32',
        status: 'Completed',
        target: 'All employees',
        date: '2026-08-10',
        completion: '100%',
        subject: 'Email subject 32',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 33,
        name: 'Phishing Simulation Campaign 33',
        status: 'Active',
        target: 'All employees',
        date: '2026-08-17',
        completion: '49%',
        subject: 'Email subject 33',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 34,
        name: 'Phishing Simulation Campaign 34',
        status: 'Draft',
        target: 'All employees',
        date: '2026-08-24',
        completion: '0%',
        subject: 'Email subject 34',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 35,
        name: 'Phishing Simulation Campaign 35',
        status: 'Completed',
        target: 'Sales Team',
        date: '2026-08-31',
        completion: '100%',
        subject: 'Email subject 35',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 36,
        name: 'Phishing Simulation Campaign 36',
        status: 'Active',
        target: 'All employees',
        date: '2026-09-07',
        completion: '21%',
        subject: 'Email subject 36',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 37,
        name: 'Phishing Simulation Campaign 37',
        status: 'Cancelled',
        target: 'All employees',
        date: '2026-09-14',
        completion: '0%',
        subject: 'Email subject 37',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 38,
        name: 'Phishing Simulation Campaign 38',
        status: 'Completed',
        target: 'Finance Team',
        date: '2026-09-21',
        completion: '100%',
        subject: 'Email subject 38',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 39,
        name: 'Phishing Simulation Campaign 39',
        status: 'Active',
        target: 'All employees',
        date: '2026-09-28',
        completion: '77%',
        subject: 'Email subject 39',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 40,
        name: 'Phishing Simulation Campaign 40',
        status: 'Draft',
        target: 'All employees',
        date: '2026-10-05',
        completion: '0%',
        subject: 'Email subject 40',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 41,
        name: 'Phishing Simulation Campaign 41',
        status: 'Completed',
        target: 'All employees',
        date: '2026-10-12',
        completion: '100%',
        subject: 'Email subject 41',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 42,
        name: 'Phishing Simulation Campaign 42',
        status: 'Active',
        target: 'IT Department',
        date: '2026-10-19',
        completion: '91%',
        subject: 'Email subject 42',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 43,
        name: 'Phishing Simulation Campaign 43',
        status: 'Cancelled',
        target: 'All employees',
        date: '2026-10-26',
        completion: '0%',
        subject: 'Email subject 43',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 44,
        name: 'Phishing Simulation Campaign 44',
        status: 'Completed',
        target: 'HR Department',
        date: '2026-11-02',
        completion: '100%',
        subject: 'Email subject 44',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 45,
        name: 'Phishing Simulation Campaign 45',
        status: 'Draft',
        target: 'All employees',
        date: '2026-11-09',
        completion: '0%',
        subject: 'Email subject 45',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 46,
        name: 'Phishing Simulation Campaign 46',
        status: 'Active',
        target: 'All employees',
        date: '2026-11-16',
        completion: '33%',
        subject: 'Email subject 46',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 47,
        name: 'Phishing Simulation Campaign 47',
        status: 'Completed',
        target: 'Executive Board',
        date: '2026-11-23',
        completion: '100%',
        subject: 'Email subject 47',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 48,
        name: 'Phishing Simulation Campaign 48',
        status: 'Cancelled',
        target: 'All employees',
        date: '2026-11-30',
        completion: '0%',
        subject: 'Email subject 48',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 49,
        name: 'Phishing Simulation Campaign 49',
        status: 'Active',
        target: 'Sales Team',
        date: '2026-12-07',
        completion: '58%',
        subject: 'Email subject 49',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
    {
        id: 50,
        name: 'Phishing Simulation Campaign 50',
        status: 'Completed',
        target: 'All employees',
        date: '2026-12-14',
        completion: '100%',
        subject: 'Email subject 50',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    },
]
