# Generated by Django 5.2.1 on 2026-03-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='PhishingOps', max_length=255)),
                ('platform_base_url', models.URLField(default='http://127.0.0.1:8000', help_text='Full URL used to build phishing links sent to employees.')),
                ('frontend_url', models.URLField(default='http://localhost:5173', help_text='React frontend URL — employees are redirected here after clicking a link.')),
                ('default_from_name', models.CharField(default='IT Security Team', help_text='Default sender display name pre-filled when creating campaigns.', max_length=255)),
                ('session_expiry_days', models.PositiveIntegerField(default=7, help_text='How many days a phishing link remains valid after being clicked.')),
                ('allow_quiz_retake', models.BooleanField(default=False, help_text='Allow employees to retake a quiz after failing.')),
                ('lms_path', models.CharField(default='lms', help_text='Frontend path employees land on after clicking a phishing link. Do NOT include slashes — e.g. "lms", "training", "courses". The final URL will be: {frontend_url}/{lms_path}?token={uuid}', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
