# Generated by Django 6.0.3 on 2026-03-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='lms_path',
            field=models.CharField(blank=True, default='', help_text='Frontend path employees land on after clicking a phishing link. Do NOT include slashes — e.g. "lms", "training", "courses". Leave blank to redirect to the root: {frontend_url}/?token={uuid}', max_length=100),
        ),
    ]
